### PR TITLE
vnc to flv to gif

### PR DESCRIPTION
**Pull request by vprusa**
test gifs deployment

### CODE REVIEW

**Comment by vprusa** [comment]
ok to test

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Build Status Message: Build Result Message<br> 
Test FAILed. Browser: Firefox 
<br> HTML_SNIPPET: ${HTML_SNIPPET}

**Comment by hawkularqe** [comment]
Build Status Message: Build Result Message<br> 
Test FAILed. Browser: Firefox 
<br> HTML_SNIPPET: <br>

**Comment by vprusa** [comment]
test this please

**Comment by vprusa** [comment]
ok to test

**Comment by hawkularqe** [comment]
Build Status Message: Build Result Message<br> 
Test PASSed. Browser: Firefox
<br> HTML_SNIPPET: <img alt='/home/hudson/workspace/vprusa-miq-mw-ui-tests/records/out_test_test.gif' src='data:image/png;base64,R0lGODlhAAQAA3cAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQICgAAACwAAAAAAAQAA4cAAAC7u7si

**Comment by hawkularqe** [comment]
Build Status Message: Build Result Message<br> 
Test PASSed. Browser: Firefox
<br> HTML_SNIPPET: <img alt='/home/hudson/workspace/vprusa-miq-mw-ui-tests/records/out_test_test.gif' src='data:image/png;base64,R0lGODlhAAQAA3cAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQICgAAACwAAAAAAAQAA4cAAAC7u7si

**Comment by vprusa** [comment]
test this please

**Comment by vprusa** [comment]
- [out_test_test](http://10.16.23.184/records/31/out_test_test.gif) <br> [out_test_test](http://10.16.23.184/records/31/out_test_test.gif)

**Comment by vprusa** [comment]
### Gif records <br>-a <br>-b

**Comment by vprusa** [comment]
ok to test

**Comment by hawkularqe** [comment]
Test PASSed.
<br> Gif records:<br> - ['out_test_test.gif']('10.16.23.184/records/32/out_test_test.gif') <br>

**Comment by vprusa** [comment]
test this please

**Comment by vprusa** [comment]
ok to test

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test PASSed.
<br> Gif records:<br> - [out_test_test.gif](http://10.16.23.184/records/33/out_test_test.gif) <br>

**Comment by vprusa** [comment]
ok to test
test this please

**Comment by vprusa** [comment]
ok to test

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test FAILed.
<br> Gif records:<br> - [*.gif](http://10.16.23.184/records/34/*.gif) <br>

**Comment by hawkularqe** [comment]
Test FAILed.
<br> ${HTML_SNIPPET}

**Comment by vprusa** [comment]
ok to test

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test PASSed.
<br> ${HTML_SNIPPET}

**Comment by vprusa** [comment]
test this please

**Comment by vprusa** [comment]
ok to test

**Comment by hawkularqe** [comment]
Test FAILed.
<br> ${HTML_SNIPPET}

**Comment by vprusa** [comment]
ok to test


test this please

**Comment by hawkularqe** [comment]
Test PASSed.
<br> Gif records:<br> - [out_test_test.gif](http://10.16.23.184/records/39/out_test_test.gif) <br>

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test FAILed.
<br> No gifs

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test PASSed.
<br> Gif records:<br> - [test_test.gif](http://10.16.23.184/records/47/test_test.gif) <br>

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test PASSed.
<br> Gif records:<br> - [test_test.gif](http://10.16.23.184/records/48/test_test.gif) <br>

**Comment by hawkularqe** [comment]
Test PASSed.
<br> Gif records:<br> - [test_test.gif](http://10.16.23.184/records/49/test_test.gif) <br>

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test FAILed.
<br> Gif records:<br> - [*.gif](http://10.16.23.184/records/52/*.gif) <br>

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test PASSed.
<br> Gif records:<br> - [out_test_test.gif](http://10.16.23.184/records/53/out_test_test.gif) <br>

**Comment by hawkularqe** [comment]
Test FAILed.
<br> No gifs

**Comment by vprusa** [comment]
ok to test

test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 55
<br> Gif records:<br> - [*.gif](http://10.16.23.184/records/55/*.gif) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 62
<br> No gifs

**Comment by vprusa** [comment]
ok to test

test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 65
<br> No gifs

**Comment by vprusa** [comment]
ok to test

test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 66
<br> No gifs

**Comment by vprusa** [comment]
ok to test

test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 67
<br> Gif records:<br> - [record_test_failing.gif](http://10.16.23.184/records/67/record_test_failing.gif) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 68
<br> Gif records:<br> - [*.gif](http://10.16.23.184/records/68/*.gif) <br>

**Comment by vprusa** [comment]
ok to test

test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 69
<br> Gif records:<br> - [record_test_failing.gif](http://10.16.23.184/records/69/record_test_failing.gif) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 71
<br> No gifs

**Comment by vprusa** [comment]
ok to test

test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 72
<br> Gif records:<br> - [record_test_deployments.gif](http://10.16.23.184/records/72/record_test_deployments.gif) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 73
<br> Gif records:<br> - [record_test_failing.gif](http://10.16.23.184/records/73/record_test_failing.gif) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 74
<br> Gif records:<br> - [record_test_failing.gif](http://10.16.23.184/records/74/record_test_failing.gif) [record_test_failing.flv](http://10.16.23.184/records/74/record_test_failing.flv) <br>

**Comment by vprusa** [comment]
ok to test

test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 75
<br> Gif records:<br> - [record_test_deployments.gif](http://10.16.23.184/records/75/record_test_deployments.gif) [record_test_deployments.flv](http://10.16.23.184/records/75/record_test_deployments.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 76
<br> Gif records:<br> - [record_test_deployments.gif](http://10.16.23.184/records/76/record_test_deployments.gif) [record_test_deployments.flv](http://10.16.23.184/records/76/record_test_deployments.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 77
<br> Gif records:<br> - [*.gif](http://10.16.23.184/records/77/*.gif) [*.flv](http://10.16.23.184/records/77/*.flv) <br>

**Comment by vprusa** [comment]
ok to test

test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 78
<br> Gif records:<br> - [record_test_failing.gif](http://10.16.23.184/records/78/record_test_failing.gif) [record_test_failing.flv](http://10.16.23.184/records/78/record_test_failing.flv) <br>

**Comment by vprusa** [comment]
ok to test

test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 79
<br> Gif records:<br> - [record_test_deployments.gif](http://10.16.23.184/records/79/record_test_deployments.gif) [record_test_deployments.flv](http://10.16.23.184/records/79/record_test_deployments.flv) <br>

**Comment by vprusa** [comment]
ok to test

test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 80
<br> Gif records:<br> - [record_test_deployments.gif](http://10.16.23.184/records/80/record_test_deployments.gif) [record_test_deployments.flv](http://10.16.23.184/records/80/record_test_deployments.flv) <br> - [record_test_providers.gif](http://10.16.23.184/records/80/record_test_providers.gif) [record_test_providers.flv](http://10.16.23.184/records/80/record_test_providers.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 81
<br> Gif records:<br> - [record_test_deployments.gif](http://10.16.23.184/records/81/record_test_deployments.gif) [record_test_deployments.flv](http://10.16.23.184/records/81/record_test_deployments.flv) <br> - [record_test_providers.gif](http://10.16.23.184/records/81/record_test_providers.gif) [record_test_providers.flv](http://10.16.23.184/records/81/record_test_providers.flv) <br> - [record_test_servers.gif](http://10.16.23.184/records/81/record_test_servers.gif) [record_test_servers.flv](http://10.16.23.184/records/81/record_test_servers.flv) <br> - [record_test_topology.gif](http://10.16.23.184/records/81/record_test_topology.gif) [record_test_topology.flv](http://10.16.23.184/records/81/record_test_topology.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: 83
<br> Gif records:<br> - [record_test_failing.gif](http://10.16.23.184/records/83/record_test_failing.gif) [record_test_failing.flv](http://10.16.23.184/records/83/record_test_failing.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [84](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/vprusa-miq-mw-ui-tests/84/)
<br> Gif records:<br> - [record_test_failing.gif](http://10.16.23.184/records/84/record_test_failing.gif) [record_test_failing.flv](http://10.16.23.184/records/84/record_test_failing.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [86](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/vprusa-miq-mw-ui-tests/86/)
<br> Gif records:<br> - [*.gif](http://10.16.23.184/records/86/*.gif) [*.flv](http://10.16.23.184/records/86/*.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [87](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/vprusa-miq-mw-ui-tests/87/)
<br> Gif records:<br> - [*.gif](http://10.16.23.184/records/87/*.gif) [*.flv](http://10.16.23.184/records/87/*.flv) <br>

**Comment by vprusa** [comment]
ok to test

test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [88](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/vprusa-miq-mw-ui-tests/88/)
<br> Gif records:<br> - [*.gif](http://10.16.23.184/records/88/*.gif) [*.flv](http://10.16.23.184/records/88/*.flv) <br>

**Comment by vprusa** [comment]
ok to test

test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [89](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/vprusa-miq-mw-ui-tests/89/)
<br> Gif records:<br> - [*.gif](http://10.16.23.184/records/89/*.gif) [*.flv](http://10.16.23.184/records/89/*.flv) <br>

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [90](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/vprusa-miq-mw-ui-tests/90/)
<br> Gif records:<br> - [*.gif](http://10.16.23.184/records/90/*.gif) [*.flv](http://10.16.23.184/records/90/*.flv) <br>

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [91](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/vprusa-miq-mw-ui-tests/91/)
<br> Gif records:<br> - [*.gif](http://10.16.23.184/records/91/*.gif) [*.flv](http://10.16.23.184/records/91/*.flv) <br>

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [92](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/vprusa-miq-mw-ui-tests/92/)
<br> Gif records:<br>

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [93](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/vprusa-miq-mw-ui-tests/93/)
<br> Gif records:<br>

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [94](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/vprusa-miq-mw-ui-tests/94/)
<br> Gif records:<br> - [record_test_failing.gif](http://10.16.23.184/records/94/record_test_failing.gif) [record_test_failing.flv](http://10.16.23.184/records/94/record_test_failing.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [95](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/vprusa-miq-mw-ui-tests/95/)
<br> Gif records:<br> - [record_test_failing.gif](http://10.16.23.184/records/95/record_test_failing.gif) [record_test_failing.flv](http://10.16.23.184/records/95/record_test_failing.flv) <br>

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [96](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/vprusa-miq-mw-ui-tests/96/)
<br> Gif records:<br>

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [97](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/vprusa-miq-mw-ui-tests/97/)
<br> Gif records:<br> - [record_test_deployments.gif](http://10.16.23.184/records/97/record_test_deployments.gif) [record_test_deployments.flv](http://10.16.23.184/records/97/record_test_deployments.flv) <br> - [record_test_providers.gif](http://10.16.23.184/records/97/record_test_providers.gif) [record_test_providers.flv](http://10.16.23.184/records/97/record_test_providers.flv) <br> - [record_test_servers.gif](http://10.16.23.184/records/97/record_test_servers.gif) [record_test_servers.flv](http://10.16.23.184/records/97/record_test_servers.flv) <br> - [record_test_topology.gif](http://10.16.23.184/records/97/record_test_topology.gif) [record_test_topology.flv](http://10.16.23.184/records/97/record_test_topology.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [106](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/vprusa-miq-mw-ui-tests/106/)
<br> Gif records:<br> - [record_test_failing.gif](http://10.16.23.184/records/106/record_test_failing.gif) [record_test_failing.flv](http://10.16.23.184/records/106/record_test_failing.flv) <br>

**Comment by vprusa** [comment]
ok to test

test this please

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [108](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/vprusa-miq-mw-ui-tests/108/)
<br> Gif records:<br> - [record_test_failing.gif](http://10.16.23.184/records/108/record_test_failing.gif) [record_test_failing.flv](http://10.16.23.184/records/108/record_test_failing.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [109](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/vprusa-miq-mw-ui-tests/109/)
<br> Gif records:<br> - [record_test_failing.gif](http://10.16.23.184/records/109/record_test_failing.gif) [record_test_failing.flv](http://10.16.23.184/records/109/record_test_failing.flv) <br>

**Comment by hawkularqe** [comment]
Test FAILed.<br>
BuildID: [2](http://jenkins.jonqe.lab.eng.bos.redhat.com:9080/job/vprusa-miq-mw-ui-tests/2/)
<br> Gif records:<br>

**Pull request merged**
