### PR TITLE
vnc to flv to gif

### PR DESCRIPTION
**Pull request by vprusa**
Quick fix #1-#4
Browser to default

### CODE REVIEW

**Comment by vprusa** [comment]
ok to test

**Comment by vprusa** [comment]
test this please

**Comment by hawkularqe** [comment]
Build Status Message: Build Result Message<br> 
Test FAILed. Browser: Firefox 
<br> HTML_SNIPPET: <a href='localhost'>Link</a>

**Comment by vprusa** [comment]
ok to test

**Comment by vprusa** [comment]
test this please

**Pull request closed without merging**
